"""initial schema

Revision ID: 7d52e0dde151
Revises:
Create Date: 2026-07-22 17:32:14.068954
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = "7d52e0dde151"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluation_cases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_key", sa.String(length=80), nullable=False),
        sa.Column("suite", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "request_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "expectations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evaluation_cases_case_key"), "evaluation_cases", ["case_key"], unique=True
    )
    op.create_index(op.f("ix_evaluation_cases_suite"), "evaluation_cases", ["suite"], unique=False)
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("suite", sa.String(length=40), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Integer(), nullable=False),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("git_ref", sa.String(length=60), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evaluation_runs_suite"), "evaluation_runs", ["suite"], unique=False)
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prompt_versions_name"), "prompt_versions", ["name"], unique=False)
    op.create_index("uq_prompt_name_version", "prompt_versions", ["name", "version"], unique=True)
    op.create_table(
        "rag_documents",
        sa.Column("document_id", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("destination", sa.String(length=80), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("source_note", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("document_id"),
    )
    op.create_index(
        op.f("ix_rag_documents_destination"), "rag_documents", ["destination"], unique=False
    )
    op.create_table(
        "tool_audits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trip_id", sa.String(length=60), nullable=True),
        sa.Column("agent_name", sa.String(length=80), nullable=False),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "arguments_redacted",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tool_audits_tool_name"), "tool_audits", ["tool_name"], unique=False)
    op.create_index(op.f("ix_tool_audits_trip_id"), "tool_audits", ["trip_id"], unique=False)
    op.create_table(
        "trips",
        sa.Column("trip_id", sa.String(length=60), nullable=False),
        sa.Column("request_id", sa.String(length=60), nullable=False),
        sa.Column("user_reference", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("origin", sa.String(length=80), nullable=False),
        sa.Column("destination", sa.String(length=80), nullable=False),
        sa.Column("cache_key", sa.String(length=80), nullable=True),
        sa.Column(
            "request_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "plan_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("replans", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("trip_id"),
    )
    op.create_index(op.f("ix_trips_cache_key"), "trips", ["cache_key"], unique=False)
    op.create_index(op.f("ix_trips_destination"), "trips", ["destination"], unique=False)
    op.create_index(op.f("ix_trips_request_id"), "trips", ["request_id"], unique=False)
    op.create_index(op.f("ix_trips_status"), "trips", ["status"], unique=False)
    op.create_index(op.f("ix_trips_user_reference"), "trips", ["user_reference"], unique=False)
    op.create_table(
        "agent_executions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trip_id", sa.String(length=60), nullable=False),
        sa.Column("task_id", sa.String(length=60), nullable=False),
        sa.Column("agent_name", sa.String(length=80), nullable=False),
        sa.Column("skill", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("tool_call_count", sa.Integer(), nullable=False),
        sa.Column("llm_call_count", sa.Integer(), nullable=False),
        sa.Column("used_mock_data", sa.Boolean(), nullable=False),
        sa.Column(
            "action_summaries",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.trip_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_executions_task_id"), "agent_executions", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_executions_trip_id"), "agent_executions", ["trip_id"], unique=False
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trip_id", sa.String(length=60), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.trip_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedback_trip_id"), "feedback", ["trip_id"], unique=False)
    op.create_table(
        "rag_chunks",
        sa.Column("chunk_id", sa.String(length=120), nullable=False),
        sa.Column("document_id", sa.String(length=120), nullable=False),
        sa.Column("citation_id", sa.String(length=40), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["rag_documents.document_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("chunk_id"),
    )
    op.create_index(op.f("ix_rag_chunks_document_id"), "rag_chunks", ["document_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rag_chunks_document_id"), table_name="rag_chunks")
    op.drop_table("rag_chunks")
    op.drop_index(op.f("ix_feedback_trip_id"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_index(op.f("ix_agent_executions_trip_id"), table_name="agent_executions")
    op.drop_index(op.f("ix_agent_executions_task_id"), table_name="agent_executions")
    op.drop_table("agent_executions")
    op.drop_index(op.f("ix_trips_user_reference"), table_name="trips")
    op.drop_index(op.f("ix_trips_status"), table_name="trips")
    op.drop_index(op.f("ix_trips_request_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_destination"), table_name="trips")
    op.drop_index(op.f("ix_trips_cache_key"), table_name="trips")
    op.drop_table("trips")
    op.drop_index(op.f("ix_tool_audits_trip_id"), table_name="tool_audits")
    op.drop_index(op.f("ix_tool_audits_tool_name"), table_name="tool_audits")
    op.drop_table("tool_audits")
    op.drop_index(op.f("ix_rag_documents_destination"), table_name="rag_documents")
    op.drop_table("rag_documents")
    op.drop_index("uq_prompt_name_version", table_name="prompt_versions")
    op.drop_index(op.f("ix_prompt_versions_name"), table_name="prompt_versions")
    op.drop_table("prompt_versions")
    op.drop_index(op.f("ix_evaluation_runs_suite"), table_name="evaluation_runs")
    op.drop_table("evaluation_runs")
    op.drop_index(op.f("ix_evaluation_cases_suite"), table_name="evaluation_cases")
    op.drop_index(op.f("ix_evaluation_cases_case_key"), table_name="evaluation_cases")
    op.drop_table("evaluation_cases")
    # ### end Alembic commands ###
