"""Deterministic mock transport provider.

No free API offers real rail, coach, or flight inventory, and scraping the operators is
prohibited — so transport offers are generated (ADR-010). Every record this provider
returns carries ``DataOrigin.MOCKED`` and is labelled in the API and the UI.

Determinism
-----------
Output is seeded from ``(origin, destination, date, travellers)``. The same query always
produces byte-identical offers, on any machine, forever. That is what makes the cache
demo, the evaluation suite, and the regression gates meaningful — a random generator would
make every assertion about ranking a coin flip.

Realism
-------
The generator is grounded in a small table of real inter-city distances and plausible
per-kilometre pricing, so a Nuremberg–Prague coach costs roughly what a coach costs. This
is *plausibility*, not truth: none of these services exist. Never present a figure from
here as a real price.
"""

from __future__ import annotations

import hashlib
from datetime import UTC, datetime, timedelta
from decimal import Decimal

from vm_contracts.common import (
    AccessibilityNeed,
    DataOrigin,
    Money,
    Provenance,
    TransportMode,
)
from vm_contracts.offers import TransportLeg, TransportOffer
from vm_domain.providers.base import ProviderResult, TransportQuery

__all__ = ["MockTransportProvider"]

SOURCE_NAME = "VoyageMesh deterministic mock transport provider"

# Approximate road/rail distances in km between cities the demo scenarios use. Unknown
# pairs fall back to a seeded distance, so the provider works for any input.
_KNOWN_DISTANCES: dict[frozenset[str], int] = {
    frozenset({"nuremberg", "prague"}): 300,
    frozenset({"nuremberg", "munich"}): 170,
    frozenset({"nuremberg", "berlin"}): 440,
    frozenset({"nuremberg", "vienna"}): 480,
    frozenset({"berlin", "prague"}): 350,
    frozenset({"munich", "prague"}): 380,
    frozenset({"vienna", "prague"}): 330,
    frozenset({"paris", "london"}): 460,
    frozenset({"amsterdam", "berlin"}): 660,
}

# Per-mode economics. Speeds are effective door-to-door averages including stops, which is
# why coach (75 km/h) sits well below motorway speed.
_MODE_PROFILE: dict[TransportMode, dict[str, float]] = {
    TransportMode.BUS: {"kmh": 75.0, "per_km": 0.055, "base": 4.0, "min_price": 12.0},
    TransportMode.TRAIN: {"kmh": 105.0, "per_km": 0.115, "base": 8.0, "min_price": 19.0},
    TransportMode.FLIGHT: {"kmh": 480.0, "per_km": 0.085, "base": 45.0, "min_price": 55.0},
}

_CARRIERS: dict[TransportMode, tuple[str, ...]] = {
    TransportMode.BUS: ("MeshCoach", "EuroLine Mock", "CityHopper Mock"),
    TransportMode.TRAIN: ("MeshRail", "Continental Mock Rail", "RegioMesh"),
    TransportMode.FLIGHT: ("MeshAir", "Continental Mock Air"),
}

# Flights only make sense beyond a certain distance; below it, city-centre-to-city-centre
# rail is faster once airport transfers are counted.
_MIN_FLIGHT_DISTANCE_KM = 500


class MockTransportProvider:
    """Generates plausible, clearly-labelled transport offers."""

    name = "mock_transport"

    def __init__(self, *, offers_per_mode: int = 3) -> None:
        self._offers_per_mode = max(1, offers_per_mode)

    async def search(self, query: TransportQuery) -> ProviderResult[TransportOffer]:
        distance = _distance_km(query.origin, query.destination)
        seed = _seed(query)

        modes = self._modes_for(query, distance)
        offers: list[TransportOffer] = []

        for mode_index, mode in enumerate(modes):
            for variant in range(self._offers_per_mode):
                offer = self._build_offer(
                    query=query,
                    mode=mode,
                    distance_km=distance,
                    seed=seed,
                    mode_index=mode_index,
                    variant=variant,
                )
                if offer is not None:
                    offers.append(offer)

        warnings = [
            "Transport options are generated by a deterministic mock provider. They are "
            "plausible but not real: no such service, schedule, or price exists."
        ]
        return ProviderResult(
            items=offers,
            origin=DataOrigin.MOCKED,
            source_name=SOURCE_NAME,
            warnings=warnings,
        )

    def _modes_for(self, query: TransportQuery, distance: int) -> list[TransportMode]:
        if query.preferred_mode is not TransportMode.ANY:
            return [query.preferred_mode] if query.preferred_mode in _MODE_PROFILE else []

        modes = [TransportMode.BUS, TransportMode.TRAIN]
        if distance >= _MIN_FLIGHT_DISTANCE_KM:
            modes.append(TransportMode.FLIGHT)
        return modes

    def _build_offer(
        self,
        *,
        query: TransportQuery,
        mode: TransportMode,
        distance_km: int,
        seed: int,
        mode_index: int,
        variant: int,
    ) -> TransportOffer | None:
        profile = _MODE_PROFILE.get(mode)
        if profile is None:
            return None

        # All variation derives from the seed, so results are stable across runs while
        # still differing meaningfully between queries.
        jitter = _jitter(seed, mode_index * 10 + variant)

        # Later variants are progressively cheaper but slower — the classic real-world
        # trade-off, and what makes the ranking strategies produce different winners.
        speed_factor = 1.0 + (variant * 0.16) + (jitter * 0.10)
        price_factor = 1.0 - (variant * 0.13) + (jitter * 0.12)

        duration_minutes = int((distance_km / profile["kmh"]) * 60 * speed_factor)
        if mode is TransportMode.FLIGHT:
            duration_minutes += 150  # airport transfers, security, boarding

        duration_minutes = max(25, duration_minutes)

        per_traveller = max(
            profile["min_price"],
            (profile["base"] + distance_km * profile["per_km"]) * price_factor,
        )
        price_per_traveller = Money.of(Decimal(str(round(per_traveller, 2))), query.currency)
        total_price = price_per_traveller.times(query.travellers)

        # Departure hour cycles through a realistic spread so schedule_inconvenience has
        # something to discriminate on.
        departure_hour = (5 + (variant * 4) + (seed % 3)) % 22
        departure = datetime.combine(
            query.departure_date, datetime.min.time(), tzinfo=UTC
        ) + timedelta(hours=departure_hour, minutes=(seed % 4) * 15)

        transfers = 0 if variant == 0 else min(variant, 2)
        legs = _build_legs(
            query=query,
            mode=mode,
            departure=departure,
            duration_minutes=duration_minutes,
            transfers=transfers,
            carrier=_CARRIERS[mode][(seed + variant) % len(_CARRIERS[mode])],
            seed=seed,
        )

        accessibility = _accessibility_for(mode, seed, variant)

        return TransportOffer(
            offer_id=f"mock-{mode.value}-{seed:08x}-{mode_index}{variant}",
            legs=legs,
            total_price=total_price,
            price_per_traveller=price_per_traveller,
            travellers=query.travellers,
            provenance=Provenance.mocked(
                SOURCE_NAME, source_id=f"{mode.value}/{seed:08x}/{mode_index}{variant}"
            ),
            accessibility_features=accessibility,
            booking_reference_url=None,  # mock offers are not bookable anywhere
        )


def _build_legs(
    *,
    query: TransportQuery,
    mode: TransportMode,
    departure: datetime,
    duration_minutes: int,
    transfers: int,
    carrier: str,
    seed: int,
) -> list[TransportLeg]:
    """Split a journey into ``transfers + 1`` legs with realistic layovers."""
    segments = transfers + 1
    if segments == 1:
        return [
            TransportLeg(
                mode=mode,
                carrier=carrier,
                from_location=_station(query.origin, mode),
                to_location=_station(query.destination, mode),
                departure_at=departure,
                arrival_at=departure + timedelta(minutes=duration_minutes),
                service_identifier=f"{carrier[:2].upper()}{1000 + (seed % 8999)}",
            )
        ]

    # Reserve a share of the total for layovers so the end-to-end duration stays honest.
    layover_minutes = 25 + (seed % 20)
    travel_minutes = max(segments * 20, duration_minutes - layover_minutes * transfers)
    per_segment = travel_minutes // segments

    legs: list[TransportLeg] = []
    cursor = departure
    for index in range(segments):
        origin_name = _station(query.origin, mode) if index == 0 else f"Interchange {index}"
        destination_name = (
            _station(query.destination, mode)
            if index == segments - 1
            else f"Interchange {index + 1}"
        )
        arrival = cursor + timedelta(minutes=per_segment)
        legs.append(
            TransportLeg(
                mode=mode,
                carrier=carrier,
                from_location=origin_name,
                to_location=destination_name,
                departure_at=cursor,
                arrival_at=arrival,
                service_identifier=f"{carrier[:2].upper()}{1000 + ((seed + index) % 8999)}",
            )
        )
        cursor = arrival + timedelta(minutes=layover_minutes)

    return legs


def _station(city: str, mode: TransportMode) -> str:
    suffix = {
        TransportMode.TRAIN: "Central Station",
        TransportMode.BUS: "Coach Terminal",
        TransportMode.FLIGHT: "Airport",
    }.get(mode, "")
    return f"{city.title()} {suffix}".strip()


def _accessibility_for(mode: TransportMode, seed: int, variant: int) -> list[AccessibilityNeed]:
    """Assign plausible accessibility features.

    Not every option is accessible — that is the point. If every mock offer satisfied every
    need, the accessibility filter would never actually exclude anything and the feature
    would be untested against real behaviour.
    """
    features: list[AccessibilityNeed] = []
    marker = (seed >> (variant + 1)) & 0b111

    if mode is TransportMode.TRAIN or marker & 0b001:
        features.append(AccessibilityNeed.STEP_FREE_ACCESS)
    if marker & 0b010:
        features.append(AccessibilityNeed.WHEELCHAIR_ACCESSIBLE)
    if mode is not TransportMode.BUS or marker & 0b100:
        features.append(AccessibilityNeed.SERVICE_ANIMAL_FRIENDLY)
    return features


def _distance_km(origin: str, destination: str) -> int:
    """Real distance where known, otherwise a stable seeded value."""
    key = frozenset({origin.strip().casefold(), destination.strip().casefold()})
    known = _KNOWN_DISTANCES.get(key)
    if known is not None:
        return known
    digest = hashlib.sha256("|".join(sorted(key)).encode()).digest()
    return 120 + (int.from_bytes(digest[:4], "big") % 900)


def _seed(query: TransportQuery) -> int:
    payload = "|".join(
        [
            query.origin.strip().casefold(),
            query.destination.strip().casefold(),
            query.departure_date.isoformat(),
            str(query.travellers),
            query.currency.value,
        ]
    )
    return int.from_bytes(hashlib.sha256(payload.encode()).digest()[:4], "big")


def _jitter(seed: int, salt: int) -> float:
    """Stable pseudo-random value in ``[-0.5, 0.5]``.

    Derived from SHA-256 rather than :mod:`random` so it depends on nothing but its
    arguments — no global RNG state, no reseeding, no ordering effects.
    """
    digest = hashlib.sha256(f"{seed}:{salt}".encode()).digest()
    return (int.from_bytes(digest[:4], "big") / 0xFFFFFFFF) - 0.5
