"""Deterministic mock accommodation provider.

Same rationale and same rules as the transport mock (ADR-010): no free API offers real
hotel inventory, scraping is prohibited, so offers are generated, seeded, and labelled
``MOCKED`` everywhere they appear. None of these properties exist.

Property names are deliberately obvious inventions ("Mesh Hostel Old Town") rather than
plausible-sounding real names. A user glancing at the results should never mistake one for
a bookable property, and a name that looks real would undermine the badge in the UI.
"""

from __future__ import annotations

import hashlib
import math
from datetime import UTC, datetime, timedelta
from decimal import Decimal

from vm_contracts.common import (
    AccessibilityNeed,
    AccommodationType,
    DataOrigin,
    GeoPoint,
    Money,
    Provenance,
)
from vm_contracts.offers import AccommodationOffer, CancellationPolicy
from vm_domain.providers.base import AccommodationQuery, ProviderResult

__all__ = ["MockAccommodationProvider"]

SOURCE_NAME = "VoyageMesh deterministic mock accommodation provider"

# Nightly rate bands per traveller, in the request currency. Grounded in typical European
# city pricing so budgets behave realistically against the demo scenarios.
_TYPE_PROFILE: dict[AccommodationType, dict[str, float]] = {
    AccommodationType.HOSTEL: {"base": 26.0, "spread": 12.0, "rating": 7.9},
    AccommodationType.BUDGET_HOTEL: {"base": 58.0, "spread": 22.0, "rating": 8.1},
    AccommodationType.GUESTHOUSE: {"base": 64.0, "spread": 24.0, "rating": 8.5},
    AccommodationType.APARTMENT: {"base": 78.0, "spread": 34.0, "rating": 8.7},
    AccommodationType.HOTEL: {"base": 112.0, "spread": 55.0, "rating": 8.4},
}

_DISTRICTS = (
    "Old Town",
    "Riverside",
    "Station Quarter",
    "Museum District",
    "Park Side",
    "Market Square",
)

_AMENITIES = (
    "wifi",
    "24h reception",
    "luggage storage",
    "breakfast available",
    "shared kitchen",
    "laundry",
    "air conditioning",
    "bike rental",
)

# When the traveller expresses no preference, offer a spread across the budget tiers so
# the ranking has something meaningful to discriminate between.
_DEFAULT_TYPE_MIX = (
    AccommodationType.HOSTEL,
    AccommodationType.BUDGET_HOTEL,
    AccommodationType.GUESTHOUSE,
    AccommodationType.APARTMENT,
    AccommodationType.HOTEL,
)


class MockAccommodationProvider:
    """Generates plausible, clearly-labelled accommodation offers."""

    name = "mock_accommodation"

    def __init__(self, *, offers_per_type: int = 2) -> None:
        self._offers_per_type = max(1, offers_per_type)

    async def search(self, query: AccommodationQuery) -> ProviderResult[AccommodationOffer]:
        nights = query.nights
        if nights <= 0:
            return ProviderResult(
                items=[],
                origin=DataOrigin.MOCKED,
                source_name=SOURCE_NAME,
                warnings=["Day trip — no overnight stay required."],
            )

        seed = _seed(query)
        centre = _city_centre(query.destination)
        types = (
            [query.accommodation_type]
            if query.accommodation_type is not AccommodationType.ANY
            else list(_DEFAULT_TYPE_MIX)
        )

        offers: list[AccommodationOffer] = []
        for type_index, accommodation_type in enumerate(types):
            for variant in range(self._offers_per_type):
                offer = _build_offer(
                    query=query,
                    accommodation_type=accommodation_type,
                    nights=nights,
                    seed=seed,
                    centre=centre,
                    type_index=type_index,
                    variant=variant,
                )
                if offer is not None:
                    offers.append(offer)

        return ProviderResult(
            items=offers,
            origin=DataOrigin.MOCKED,
            source_name=SOURCE_NAME,
            warnings=[
                "Accommodation options are generated by a deterministic mock provider. "
                "These properties do not exist and cannot be booked."
            ],
        )


def _build_offer(
    *,
    query: AccommodationQuery,
    accommodation_type: AccommodationType,
    nights: int,
    seed: int,
    centre: GeoPoint,
    type_index: int,
    variant: int,
) -> AccommodationOffer | None:
    profile = _TYPE_PROFILE.get(accommodation_type)
    if profile is None:
        return None

    jitter = _jitter(seed, type_index * 10 + variant)

    # Rate rises with distance from the centre being *lower* — the classic trade-off that
    # makes the distance weight in scoring do real work.
    distance_km = round(0.4 + (variant * 1.1) + abs(jitter) * 2.2, 2)
    centrality_premium = max(0.0, 1.0 - distance_km / 6.0) * 0.35

    nightly = profile["base"] * (1.0 + centrality_premium + jitter * 0.30)
    nightly = max(9.0, nightly)

    # Guests share rooms above a threshold rather than each paying a full rate — matching
    # how hostels and family rooms actually price.
    rooms_needed = max(1, (query.guests + 1) // 2)
    if accommodation_type is AccommodationType.HOSTEL:
        nightly_total = nightly * query.guests  # per-bed pricing
    else:
        nightly_total = nightly * rooms_needed

    price_per_night = Money.of(Decimal(str(round(nightly_total, 2))), query.currency)
    total_price = price_per_night.times(nights)

    rating = round(min(9.8, max(5.5, profile["rating"] + jitter * 1.6)), 1)
    review_count = 40 + (seed + type_index * 7 + variant) % 1800

    free_cancellation = ((seed >> (type_index + variant)) & 0b11) != 0
    cancellation = CancellationPolicy(
        free_cancellation=free_cancellation,
        free_cancellation_until=(
            datetime.combine(query.check_in, datetime.min.time(), tzinfo=UTC) - timedelta(days=2)
            if free_cancellation
            else None
        ),
        description=(
            "Free cancellation until 2 days before check-in (simulated)."
            if free_cancellation
            else "Non-refundable (simulated)."
        ),
    )

    district = _DISTRICTS[(seed + type_index * 3 + variant) % len(_DISTRICTS)]
    amenity_count = 3 + ((seed >> variant) % 4)
    amenities = [
        _AMENITIES[(seed + i * 5 + variant) % len(_AMENITIES)] for i in range(amenity_count)
    ]

    return AccommodationOffer(
        offer_id=f"mock-stay-{seed:08x}-{type_index}{variant}",
        name=f"Mesh {accommodation_type.value.replace('_', ' ').title()} {district}",
        accommodation_type=accommodation_type,
        price_per_night=price_per_night,
        total_price=total_price,
        nights=nights,
        guests=query.guests,
        location=_offset_point(centre, distance_km, seed + variant),
        address=f"{1 + (seed + variant) % 120} {district} Street, {query.destination.title()}",
        distance_to_centre_km=distance_km,
        rating=rating,
        review_count=review_count,
        cancellation=cancellation,
        accessibility_features=_accessibility_for(accommodation_type, seed, variant),
        amenities=sorted(set(amenities)),
        provenance=Provenance.mocked(
            SOURCE_NAME, source_id=f"{accommodation_type.value}/{seed:08x}/{type_index}{variant}"
        ),
        booking_reference_url=None,
    )


def _accessibility_for(
    accommodation_type: AccommodationType, seed: int, variant: int
) -> list[AccessibilityNeed]:
    """Assign plausible accessibility features.

    As with transport, not every property is accessible — otherwise the accessibility
    filter would never exclude anything and would be effectively untested.
    """
    features: list[AccessibilityNeed] = []
    marker = (seed >> (variant + 2)) & 0b1111

    if marker & 0b0001 or accommodation_type in (
        AccommodationType.HOTEL,
        AccommodationType.APARTMENT,
    ):
        features.append(AccessibilityNeed.STEP_FREE_ACCESS)
    if marker & 0b0010:
        features.append(AccessibilityNeed.ELEVATOR_REQUIRED)
    if marker & 0b0100:
        features.append(AccessibilityNeed.WHEELCHAIR_ACCESSIBLE)
        features.append(AccessibilityNeed.ACCESSIBLE_BATHROOM)
    if marker & 0b1000:
        features.append(AccessibilityNeed.SERVICE_ANIMAL_FRIENDLY)
    return features


# Coordinates of city centres used by the demo scenarios. Real values — these are genuine
# facts about real places, unlike the generated properties themselves.
_CITY_CENTRES: dict[str, GeoPoint] = {
    "prague": GeoPoint(latitude=50.0875, longitude=14.4213),
    "nuremberg": GeoPoint(latitude=49.4539, longitude=11.0775),
    "munich": GeoPoint(latitude=48.1372, longitude=11.5755),
    "berlin": GeoPoint(latitude=52.5200, longitude=13.4050),
    "vienna": GeoPoint(latitude=48.2082, longitude=16.3738),
    "paris": GeoPoint(latitude=48.8566, longitude=2.3522),
    "london": GeoPoint(latitude=51.5074, longitude=-0.1278),
    "amsterdam": GeoPoint(latitude=52.3676, longitude=4.9041),
}


def _city_centre(destination: str) -> GeoPoint:
    """Real centre where known; otherwise a stable seeded point in central Europe."""
    known = _CITY_CENTRES.get(destination.strip().casefold())
    if known is not None:
        return known
    digest = hashlib.sha256(destination.strip().casefold().encode()).digest()
    lat = 45.0 + (int.from_bytes(digest[0:2], "big") / 65535) * 10.0
    lon = 5.0 + (int.from_bytes(digest[2:4], "big") / 65535) * 18.0
    return GeoPoint(latitude=round(lat, 4), longitude=round(lon, 4))


def _offset_point(centre: GeoPoint, distance_km: float, salt: int) -> GeoPoint:
    """Place a property ``distance_km`` from the centre in a stable direction."""
    bearing = math.radians(salt % 360)
    # ~111 km per degree of latitude; longitude is scaled by cos(latitude) but the small
    # distances here make the simple approximation entirely adequate.
    dlat = (distance_km / 111.0) * math.cos(bearing)
    dlon = (distance_km / 74.0) * math.sin(bearing)
    return GeoPoint(
        latitude=round(max(-90.0, min(90.0, centre.latitude + dlat)), 5),
        longitude=round(max(-180.0, min(180.0, centre.longitude + dlon)), 5),
    )


def _seed(query: AccommodationQuery) -> int:
    payload = "|".join(
        [
            query.destination.strip().casefold(),
            query.check_in.isoformat(),
            query.check_out.isoformat(),
            str(query.guests),
            query.currency.value,
        ]
    )
    return int.from_bytes(hashlib.sha256(payload.encode()).digest()[:4], "big")


def _jitter(seed: int, salt: int) -> float:
    digest = hashlib.sha256(f"stay:{seed}:{salt}".encode()).digest()
    return (int.from_bytes(digest[:4], "big") / 0xFFFFFFFF) - 0.5
