"""Shared vocabulary used by every other contract module.

Two types here carry most of the project's weight:

* :class:`Money` — an amount is *never* a bare float. Pairing the value with its currency
  at the type level is what makes the "every price includes a currency" output guardrail
  a tautology rather than a runtime check that can be forgotten.
* :class:`Provenance` — every fact that reaches the user carries where it came from, how
  it was obtained, and when. This is what allows the UI to label data `LIVE` / `CACHED` /
  `MOCKED` / `FIXTURE` honestly instead of presenting everything with equal confidence.
"""

from __future__ import annotations

from datetime import UTC, datetime
from decimal import ROUND_HALF_UP, Decimal
from enum import StrEnum
from typing import Annotated, Self

from pydantic import BaseModel, ConfigDict, Field, computed_field, field_validator, model_validator

__all__ = [
    "AccessibilityNeed",
    "AccommodationType",
    "ConfidenceLevel",
    "Currency",
    "DataOrigin",
    "GeoPoint",
    "Money",
    "Provenance",
    "RankingStrategy",
    "TransportMode",
    "utc_now",
]


def utc_now() -> datetime:
    """Timezone-aware current UTC time.

    Used everywhere instead of ``datetime.now()``: naive timestamps compared across
    service boundaries are a reliable source of off-by-hours bugs.
    """
    return datetime.now(UTC)


class StrictModel(BaseModel):
    """Base for all contract models.

    ``extra="forbid"`` is deliberate and load-bearing: an *unexpected* field in an A2A
    artifact or a provider payload is a contract violation we want to hear about loudly,
    not silently discard.

    But a model's own **computed** fields are not unexpected — ``model_dump()`` emits them,
    and re-parsing a dumped model (the exact round-trip an agent→orchestrator handoff
    performs) would otherwise fail on them. The before-validator below drops a model's own
    computed-field names from incoming data, so feeding a model its own output is a no-op
    while a genuinely unknown field still raises. Nesting is handled for free: each nested
    ``StrictModel`` strips its own computed fields as pydantic validates it.
    """

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
        str_strip_whitespace=True,
        validate_assignment=True,
        use_enum_values=False,
    )

    @model_validator(mode="before")
    @classmethod
    def _drop_own_computed_fields(cls, data: object) -> object:
        computed = cls.model_computed_fields
        if not computed or not isinstance(data, dict):
            return data
        overlap = computed.keys() & data.keys()
        if not overlap:
            return data
        return {key: value for key, value in data.items() if key not in overlap}


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------
class Currency(StrEnum):
    """ISO-4217 codes supported by the planner."""

    EUR = "EUR"
    GBP = "GBP"
    USD = "USD"
    CHF = "CHF"
    CZK = "CZK"
    PLN = "PLN"
    SEK = "SEK"
    DKK = "DKK"
    NOK = "NOK"


class DataOrigin(StrEnum):
    """How a piece of data was obtained. Rendered as a badge in the UI.

    The distinction between ``MOCKED`` and ``FIXTURE`` matters: fixtures are curated real
    facts (a museum's real address), whereas mocked records are *generated* and correspond
    to no real-world offer. Conflating them would understate how synthetic the transport
    and accommodation results are.
    """

    LIVE = "live"
    """Fetched from an external API during this request."""

    CACHED = "cached"
    """Served from Redis; originally live. ``retrieved_at`` is the original fetch time."""

    MOCKED = "mocked"
    """Generated by a deterministic mock provider. Corresponds to no real offer."""

    FIXTURE = "fixture"
    """Curated real-world reference data stored in the repository."""

    COMPUTED = "computed"
    """Derived by VoyageMesh's own deterministic code (budgets, scores, distances)."""

    UNAVAILABLE = "unavailable"
    """The source could not be reached. No data — never a fabricated substitute."""


class RankingStrategy(StrEnum):
    """How the user wants options ordered."""

    CHEAPEST = "cheapest"
    FASTEST = "fastest"
    BALANCED = "balanced"
    FEWEST_TRANSFERS = "fewest_transfers"


class TransportMode(StrEnum):
    TRAIN = "train"
    BUS = "bus"
    FLIGHT = "flight"
    CAR = "car"
    FERRY = "ferry"
    WALK = "walk"
    ANY = "any"


class AccommodationType(StrEnum):
    HOSTEL = "hostel"
    BUDGET_HOTEL = "budget_hotel"
    HOTEL = "hotel"
    APARTMENT = "apartment"
    GUESTHOUSE = "guesthouse"
    ANY = "any"


class AccessibilityNeed(StrEnum):
    """Accessibility requirements. These are *hard* constraints, never trade-offs.

    An option that fails an accessibility requirement is filtered out entirely rather than
    scored lower — ranking a step-free requirement against price would be wrong.
    """

    STEP_FREE_ACCESS = "step_free_access"
    WHEELCHAIR_ACCESSIBLE = "wheelchair_accessible"
    ELEVATOR_REQUIRED = "elevator_required"
    ACCESSIBLE_BATHROOM = "accessible_bathroom"
    LOW_WALKING_DISTANCE = "low_walking_distance"
    HEARING_ASSISTANCE = "hearing_assistance"
    VISUAL_ASSISTANCE = "visual_assistance"
    SERVICE_ANIMAL_FRIENDLY = "service_animal_friendly"


class ConfidenceLevel(StrEnum):
    """Overall trustworthiness of a result section."""

    HIGH = "high"
    """Live or curated data, complete, all constraints verified."""

    MEDIUM = "medium"
    """Mocked or partially cached data, or minor gaps."""

    LOW = "low"
    """Significant degradation — a dependency failed or constraints were relaxed."""

    NONE = "none"
    """No usable data for this section."""


# ---------------------------------------------------------------------------
# Money
# ---------------------------------------------------------------------------
class Money(StrictModel):
    """A monetary amount bound to its currency.

    Amounts use :class:`~decimal.Decimal`, not ``float``. Summing 0.1 + 0.2 in binary
    floating point and comparing the result against a budget is exactly the kind of
    quiet error this project exists to avoid.
    """

    amount: Annotated[Decimal, Field(ge=0, max_digits=12, decimal_places=2)]
    currency: Currency

    @field_validator("amount", mode="before")
    @classmethod
    def _quantize(cls, value: object) -> object:
        """Round to cents *before* the 2-dp constraint is applied.

        Two reasons this must run first. Providers legitimately return sub-cent precision
        (a per-night rate of 33.333), and rejecting those outright would be wrong — cents
        are the correct resolution for money. And normalising here makes equality and
        hashing behave: without it Decimal("10.5") != Decimal("10.50") despite being the
        same amount. The ``decimal_places=2`` constraint then acts as a post-condition.
        """
        if isinstance(value, Decimal):
            return value.quantize(Decimal("0.01"), ROUND_HALF_UP)
        if isinstance(value, int | str):
            try:
                return Decimal(value).quantize(Decimal("0.01"), ROUND_HALF_UP)
            except (ArithmeticError, ValueError):
                return value  # let pydantic produce the proper validation error
        return value

    @classmethod
    def zero(cls, currency: Currency) -> Money:
        return cls(amount=Decimal("0.00"), currency=currency)

    @classmethod
    def of(cls, amount: Decimal | int | str, currency: Currency) -> Money:
        """Construct from a plain value. Never accepts ``float`` — see class docstring."""
        return cls(amount=Decimal(str(amount)), currency=currency)

    def _require_same_currency(self, other: Money, op: str) -> None:
        if self.currency is not other.currency:
            raise ValueError(
                f"cannot {op} {self.currency.value} and {other.currency.value}: convert to a "
                f"single currency before combining amounts"
            )

    def __add__(self, other: Money) -> Money:
        self._require_same_currency(other, "add")
        return Money(amount=self.amount + other.amount, currency=self.currency)

    def __sub__(self, other: Money) -> Money:
        """Subtract. May produce a negative result, which callers must handle.

        Note the ``ge=0`` field constraint: an over-budget difference is expressed as
        :class:`~vm_contracts.budget.BudgetSummary.overspend`, a separate non-negative
        amount, rather than as negative money.
        """
        self._require_same_currency(other, "subtract")
        result = self.amount - other.amount
        if result < 0:
            raise ValueError(
                f"subtraction would yield a negative amount "
                f"({self.amount} - {other.amount}); use difference_or_zero() and inspect "
                f"exceeds() to express an overspend"
            )
        return Money(amount=result, currency=self.currency)

    def difference_or_zero(self, other: Money) -> Money:
        """``self - other``, floored at zero. Safe for 'remaining budget' calculations."""
        self._require_same_currency(other, "subtract")
        return Money(
            amount=max(Decimal("0.00"), self.amount - other.amount), currency=self.currency
        )

    def times(self, factor: int) -> Money:
        """Multiply by a whole number — nights, travellers, seats."""
        if factor < 0:
            raise ValueError("factor must be non-negative")
        return Money(amount=self.amount * factor, currency=self.currency)

    def exceeds(self, limit: Money) -> bool:
        self._require_same_currency(limit, "compare")
        return self.amount > limit.amount

    def __lt__(self, other: Money) -> bool:
        self._require_same_currency(other, "compare")
        return self.amount < other.amount

    def __le__(self, other: Money) -> bool:
        self._require_same_currency(other, "compare")
        return self.amount <= other.amount

    def __str__(self) -> str:
        return f"{self.amount:.2f} {self.currency.value}"


# ---------------------------------------------------------------------------
# Geography
# ---------------------------------------------------------------------------
class GeoPoint(StrictModel):
    """A WGS-84 coordinate."""

    latitude: Annotated[float, Field(ge=-90.0, le=90.0)]
    longitude: Annotated[float, Field(ge=-180.0, le=180.0)]

    def __str__(self) -> str:
        return f"({self.latitude:.5f}, {self.longitude:.5f})"


# ---------------------------------------------------------------------------
# Provenance
# ---------------------------------------------------------------------------
class Provenance(StrictModel):
    """Where a piece of data came from, and when.

    Attached to every offer, attraction, and forecast. The output guardrail rejects any
    record whose provenance claims :attr:`DataOrigin.LIVE` without a ``retrieved_at``
    timestamp, and the UI refuses to render an unlabelled record at all.
    """

    origin: DataOrigin
    source_name: Annotated[str, Field(min_length=1, max_length=120)]
    """Human-readable source, e.g. ``"Open-Meteo"`` or ``"VoyageMesh mock rail provider"``."""

    source_id: Annotated[str | None, Field(max_length=200)] = None
    """Stable identifier of the record within the source, used to prove an offer that
    reaches the user actually came from a provider result."""

    retrieved_at: datetime | None = None
    source_url: Annotated[str | None, Field(max_length=500)] = None
    license_note: Annotated[str | None, Field(max_length=200)] = None
    cache_age_seconds: Annotated[int | None, Field(ge=0)] = None

    @model_validator(mode="after")
    def _validate_origin_requirements(self) -> Self:
        if self.origin in (DataOrigin.LIVE, DataOrigin.CACHED) and self.retrieved_at is None:
            raise ValueError(
                f"provenance with origin={self.origin.value} must carry retrieved_at; "
                f"data claimed to come from a real source must say when it was fetched"
            )
        if self.retrieved_at is not None and self.retrieved_at.tzinfo is None:
            raise ValueError("retrieved_at must be timezone-aware (use vm_contracts.utc_now)")
        if self.origin is DataOrigin.CACHED and self.cache_age_seconds is None:
            raise ValueError("cached data must report cache_age_seconds so staleness is visible")
        return self

    @computed_field  # type: ignore[prop-decorator]
    @property
    def is_synthetic(self) -> bool:
        """True when this record corresponds to no real-world offer."""
        return self.origin is DataOrigin.MOCKED

    @computed_field  # type: ignore[prop-decorator]
    @property
    def display_label(self) -> str:
        """Uppercase badge text for the UI."""
        return self.origin.value.upper()

    @classmethod
    def live(
        cls,
        source_name: str,
        *,
        source_id: str | None = None,
        source_url: str | None = None,
        license_note: str | None = None,
    ) -> Provenance:
        return cls(
            origin=DataOrigin.LIVE,
            source_name=source_name,
            source_id=source_id,
            retrieved_at=utc_now(),
            source_url=source_url,
            license_note=license_note,
        )

    @classmethod
    def mocked(cls, source_name: str, *, source_id: str | None = None) -> Provenance:
        return cls(
            origin=DataOrigin.MOCKED,
            source_name=source_name,
            source_id=source_id,
            retrieved_at=utc_now(),
        )

    @classmethod
    def fixture(cls, source_name: str, *, source_id: str | None = None) -> Provenance:
        return cls(origin=DataOrigin.FIXTURE, source_name=source_name, source_id=source_id)

    @classmethod
    def computed(cls, source_name: str = "VoyageMesh deterministic calculation") -> Provenance:
        return cls(origin=DataOrigin.COMPUTED, source_name=source_name)

    @classmethod
    def unavailable(cls, source_name: str) -> Provenance:
        return cls(origin=DataOrigin.UNAVAILABLE, source_name=source_name)

    def as_cached(self, *, age_seconds: int) -> Provenance:
        """Return a copy re-labelled as cache-served, preserving the original fetch time."""
        return self.model_copy(
            update={"origin": DataOrigin.CACHED, "cache_age_seconds": age_seconds}
        )
