"""Transport and accommodation offers.

Every offer carries :class:`~vm_contracts.common.Provenance` and a stable ``offer_id``.
The output guardrail matches the recommended offer's ID against the provider's result set,
which is what structurally prevents an invented hotel or flight from reaching the user.

Scores are attached by the deterministic ranker in ``vm_domain.scoring`` rather than being
set by providers, so an offer cannot arrive pre-ranked in its own favour.
"""

from __future__ import annotations

from datetime import datetime
from itertools import pairwise
from typing import Annotated, Self

from pydantic import Field, computed_field, model_validator

from vm_contracts.common import (
    AccessibilityNeed,
    AccommodationType,
    GeoPoint,
    Money,
    Provenance,
    StrictModel,
    TransportMode,
)

__all__ = [
    "AccommodationOffer",
    "CancellationPolicy",
    "TransportLeg",
    "TransportOffer",
]


class TransportLeg(StrictModel):
    """One continuous segment of a journey — no change of vehicle within a leg."""

    mode: TransportMode
    carrier: Annotated[str, Field(min_length=1, max_length=100)]
    from_location: Annotated[str, Field(min_length=1, max_length=120)]
    to_location: Annotated[str, Field(min_length=1, max_length=120)]
    departure_at: datetime
    arrival_at: datetime
    service_identifier: Annotated[str | None, Field(max_length=40)] = None
    """Train/flight number where the provider supplies one."""

    @model_validator(mode="after")
    def _validate_times(self) -> Self:
        if self.departure_at.tzinfo is None or self.arrival_at.tzinfo is None:
            raise ValueError("leg times must be timezone-aware")
        if self.arrival_at <= self.departure_at:
            raise ValueError(
                f"leg arrives ({self.arrival_at.isoformat()}) at or before it departs "
                f"({self.departure_at.isoformat()})"
            )
        return self

    @computed_field  # type: ignore[prop-decorator]
    @property
    def duration_minutes(self) -> int:
        return int((self.arrival_at - self.departure_at).total_seconds() // 60)


class TransportOffer(StrictModel):
    """A complete origin-to-destination journey, priced for the whole party."""

    offer_id: Annotated[str, Field(min_length=1, max_length=120)]
    legs: Annotated[list[TransportLeg], Field(min_length=1, max_length=10)]
    return_legs: Annotated[list[TransportLeg], Field(max_length=10)] = Field(default_factory=list)
    """The return journey, priced together with the outbound in total_price."""
    expires_at: datetime | None = None
    total_price: Money
    """Total for all travellers, all legs. Per-person pricing is a common source of
    budget errors, so this field is unambiguous by name and by validation."""

    price_per_traveller: Money
    travellers: Annotated[int, Field(ge=1)]
    provenance: Provenance

    accessibility_features: list[AccessibilityNeed] = Field(default_factory=list)
    booking_reference_url: Annotated[str | None, Field(max_length=500)] = None
    """Where a human could book this themselves. Never generated by an LLM — only ever a
    provider-supplied value, and ``None`` for mock offers."""

    score: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    """Set by ``vm_domain.scoring``. Lower is better; 0.0 is the ideal option."""

    score_breakdown: dict[str, float] = Field(default_factory=dict)
    """Per-component contributions, surfaced to the user as the trade-off explanation."""

    @model_validator(mode="after")
    def _validate_journey(self) -> Self:
        if self.total_price.currency is not self.price_per_traveller.currency:
            raise ValueError("total_price and price_per_traveller must share a currency")

        expected = self.price_per_traveller.times(self.travellers)
        # One cent of tolerance per traveller absorbs legitimate rounding when a provider
        # quotes a party total that does not divide evenly.
        tolerance = self.travellers
        if abs(int(expected.amount * 100) - int(self.total_price.amount * 100)) > tolerance:
            raise ValueError(
                f"price inconsistency: {self.price_per_traveller} x {self.travellers} = "
                f"{expected}, but total_price is {self.total_price}"
            )

        if self.expires_at is not None and self.expires_at.tzinfo is None:
            raise ValueError("offer expiry must be timezone-aware")
        for earlier, later in pairwise([*self.legs, *self.return_legs]):
            if later.departure_at < earlier.arrival_at:
                raise ValueError(
                    f"impossible connection: leg departs {later.departure_at.isoformat()} "
                    f"before the previous leg arrives at {earlier.arrival_at.isoformat()}"
                )
        return self

    @computed_field  # type: ignore[prop-decorator]
    @property
    def departure_at(self) -> datetime:
        return self.legs[0].departure_at

    @computed_field  # type: ignore[prop-decorator]
    @property
    def arrival_at(self) -> datetime:
        return self.legs[-1].arrival_at

    @computed_field  # type: ignore[prop-decorator]
    @property
    def total_duration_minutes(self) -> int:
        """Door-to-door duration including waiting time at transfers.

        Deliberately measured end-to-end rather than as the sum of leg durations: a
        journey with a three-hour layover is three hours worse, and summing legs would
        hide exactly that.
        """
        return int((self.arrival_at - self.legs[0].departure_at).total_seconds() // 60)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def transfer_count(self) -> int:
        return len(self.legs) - 1

    @computed_field  # type: ignore[prop-decorator]
    @property
    def modes(self) -> list[TransportMode]:
        seen: list[TransportMode] = []
        for leg in [*self.legs, *self.return_legs]:
            if leg.mode not in seen:
                seen.append(leg.mode)
        return seen

    @computed_field  # type: ignore[prop-decorator]
    @property
    def return_duration_minutes(self) -> int:
        if not self.return_legs:
            return 0
        return int(
            (self.return_legs[-1].arrival_at - self.return_legs[0].departure_at).total_seconds()
            // 60
        )

    @computed_field  # type: ignore[prop-decorator]
    @property
    def return_transfer_count(self) -> int:
        return max(0, len(self.return_legs) - 1)

    def satisfies(
        self,
        *,
        max_duration_hours: float,
        max_transfers: int,
        accessibility_needs: list[AccessibilityNeed],
    ) -> bool:
        """Hard-constraint check. Used to filter, never to score."""
        if max(self.total_duration_minutes, self.return_duration_minutes) > max_duration_hours * 60:
            return False
        if max(self.transfer_count, self.return_transfer_count) > max_transfers:
            return False
        return all(need in self.accessibility_features for need in accessibility_needs)


class CancellationPolicy(StrictModel):
    """Cancellation terms, one of the ranking factors for accommodation."""

    free_cancellation: bool
    free_cancellation_until: datetime | None = None
    description: Annotated[str, Field(max_length=300)] = ""

    @model_validator(mode="after")
    def _validate(self) -> Self:
        if self.free_cancellation and self.free_cancellation_until is None:
            raise ValueError(
                "free_cancellation=True requires free_cancellation_until; a deadline-free "
                "cancellation claim is not something we will show a user"
            )
        return self


class AccommodationOffer(StrictModel):
    """A place to stay, priced for the entire stay rather than per night."""

    offer_id: Annotated[str, Field(min_length=1, max_length=120)]
    name: Annotated[str, Field(min_length=1, max_length=200)]
    accommodation_type: AccommodationType

    price_per_night: Money
    total_price: Money
    """Total for the whole stay and all rooms/guests. This is what enters the budget —
    ranking on nightly rate while budgeting on the total is a classic mismatch."""

    nights: Annotated[int, Field(ge=1)]
    guests: Annotated[int, Field(ge=1)]

    location: GeoPoint | None = None
    address: Annotated[str | None, Field(max_length=300)] = None
    distance_to_centre_km: Annotated[float | None, Field(ge=0, le=200)] = None
    rating: Annotated[float | None, Field(ge=0.0, le=10.0)] = None
    review_count: Annotated[int | None, Field(ge=0)] = None

    cancellation: CancellationPolicy | None = None
    accessibility_features: list[AccessibilityNeed] = Field(default_factory=list)
    amenities: Annotated[list[str], Field(max_length=30)] = Field(default_factory=list)

    provenance: Provenance
    booking_reference_url: Annotated[str | None, Field(max_length=500)] = None

    score: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    score_breakdown: dict[str, float] = Field(default_factory=dict)

    @model_validator(mode="after")
    def _validate_pricing(self) -> Self:
        if self.price_per_night.currency is not self.total_price.currency:
            raise ValueError("price_per_night and total_price must share a currency")

        expected = self.price_per_night.times(self.nights)
        tolerance = self.nights  # a cent per night
        if abs(int(expected.amount * 100) - int(self.total_price.amount * 100)) > tolerance:
            raise ValueError(
                f"price inconsistency: {self.price_per_night} x {self.nights} nights = "
                f"{expected}, but total_price is {self.total_price}"
            )
        return self

    def satisfies(self, *, accessibility_needs: list[AccessibilityNeed]) -> bool:
        return all(need in self.accessibility_features for need in accessibility_needs)
